Repository two-whales-and-one-shrimp/happy_house, pull requests merged in 2022-12, with the labels that each got.

#6 Revert 5 feature/4 스웨거제거
  server/happyhouse_server/pom.xml
Labels: feautre

#8 Feature/7 스웨거제거
  server/happyhouse_server/pom.xml
Labels: feautre

#9 Feature/1 페이지 구성
  client/happyhouse_client/src/App.vue
  client/happyhouse_client/src/assets/css/main.css
  client/happyhouse_client/src/assets/logo.svg
  client/happyhouse_client/src/components/footer/TheFooter.vue
  client/happyhouse_client/src/components/header/Avartar.vue
  client/happyhouse_client/src/components/header/Logo.vue
  client/happyhouse_client/src/components/header/TheHeader.vue
  client/happyhouse_client/src/components/home/NewsList.vue
  client/happyhouse_client/src/components/home/SearchBar.vue
  client/happyhouse_client/src/components/user/UserInfo.vue
  client/happyhouse_client/src/components/user/UserSignIn.vue
  client/happyhouse_client/src/components/user/UserSignUp.vue
  client/happyhouse_client/src/plugins/vuetify.js
  client/happyhouse_client/src/router/index.js
  client/happyhouse_client/src/views/AdminView.vue
  client/happyhouse_client/src/views/HomeView.vue
  client/happyhouse_client/src/views/MapView.vue
  client/happyhouse_client/src/views/UserView.vue
Labels: enhancement

#12 Feature/11 client-side 개행 형식 변경
  client/happyhouse_client/.gitattributes
Labels: feautre

#15 Bug/14 client router path 오류
  client/happyhouse_client/src/router/index.js
Labels: bug

#19 Feature/3 로그인
  server/happyhouse_server/pom.xml
  server/happyhouse_server/src/main/java/com/ssafy/house/HouseApplication.java
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/JWTAuthenticatioFilter.java
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/JWTProvider.java
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/dto/UserDto.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/dto/UserSignInResultDto.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/entity/User.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/repository/UserRepository.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserDetailsImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
  server/happyhouse_server/src/main/resources/application.properties
Labels: feautre

#26 Bug/25-jwt기간 만료 버그
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/JWTProvider.java
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
Labels: bug

#27 Feature/24-회원목록조회-api
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/AdminController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/dto/UserListDto.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement

#30 Feature/21 회원가입서버
  server/happyhouse_server/pom.xml
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/config/util/EmailConfig.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/repository/UserRepository.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
  server/happyhouse_server/src/main/resources/mail/mail.properties
Labels: enhancement, good first issue

#29 Feature/22 로그인 front end 제작
  client/happyhouse_client/package-lock.json
  client/happyhouse_client/package.json
  client/happyhouse_client/src/api/index.js
  client/happyhouse_client/src/api/user.js
  client/happyhouse_client/src/components/header/TheHeader.vue
  client/happyhouse_client/src/components/user/UserSignIn.vue
  client/happyhouse_client/src/router/index.js
  client/happyhouse_client/src/store/index.js
  client/happyhouse_client/src/store/modules/user-store.js
  server/happyhouse_server/src/main/java/com/ssafy/house/config/web/WebConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
Labels: feautre

#33 Feature/28-회원삭제-server
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/AdminController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement

#35 Feature/32 로그아웃
  client/happyhouse_client/src/api/index.js
  client/happyhouse_client/src/api/user.js
  client/happyhouse_client/src/components/header/TheHeader.vue
  client/happyhouse_client/src/store/modules/user-store.js
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/JWTProvider.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: feautre

#36 Feature/34-회원승격-server
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/AdminController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement

#40 Feature/37-관리자 기능 연동
  client/happyhouse_client/src/api/admin.js
  client/happyhouse_client/src/components/admin/UserList.vue
Labels: enhancement

#41 Feature/32 회원가입 client
  client/happyhouse_client/src/api/user.js
  client/happyhouse_client/src/components/user/UserSignUp.vue
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement

#43 feat : 회원 정보 삭제 server
  client/happyhouse_client/src/api/user.js
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement

#49 Feature/45 비밀번호찾기 server
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement, good first issue

#51 Feature/48 로그인수정
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/data/repository/UserRepository.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement

#55 Feature/53 header 수정 client
  client/happyhouse_client/src/api/user.js
  client/happyhouse_client/src/components/header/Avartar.vue
  client/happyhouse_client/src/store/modules/user-store.js
Labels: bug

#58 Bug/57-api token-client
  client/happyhouse_client/src/api/admin.js
Labels: bug

#54 Feature/50 회원정보수정 server
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement, good first issue

#61 Feature/56 회원정보관리연동 - client
  client/happyhouse_client/src/api/user.js
  client/happyhouse_client/src/components/user/UserInfo.vue
  client/happyhouse_client/src/components/user/UserSignIn.vue
Labels: enhancement

#64 Feature/63-이메일전송
  server/happyhouse_server/pom.xml
  server/happyhouse_server/src/main/java/com/ssafy/house/config/EmailConfig.java
  server/happyhouse_server/src/main/java/com/ssafy/house/config/RedisConfig.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/EmailUtil.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/RedisUtil.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
  server/happyhouse_server/src/main/resources/application.properties
Labels: enhancement

#69 Bug/68-is admin값가져오기
  client/happyhouse_client/src/store/modules/user-store.js
  server/happyhouse_server/src/main/java/com/ssafy/house/config/RedisConfig.java
Labels: bug

#71 Feature/67-지도 기본 화면-client
  client/happyhouse_client/src/components/map/LeftBar.vue
  client/happyhouse_client/src/components/map/TheKakaoMap.vue
  client/happyhouse_client/src/components/map/TradeSearchList.vue
  client/happyhouse_client/src/views/MapView.vue
Labels: enhancement

#70 Feature/65-내정보조회
  server/happyhouse_server/src/main/java/com/ssafy/house/user/controller/UserController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/impl/UserDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/UserService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/user/service/impl/UserServiceImpl.java
Labels: enhancement, good first issue

#74 Feature/73-검색어자동완성-server
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/controller/MapController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/dao/MapDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/dao/impl/MapDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/data/entity/Gugun.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/data/repository/MapRepository.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/service/MapService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/service/impl/MapServiceImpl.java
Labels: enhancement, good first issue

#75 Feature/72-내정보연동-client
  client/happyhouse_client/src/api/user.js
  client/happyhouse_client/src/components/user/UserInfo.vue
Labels: enhancement

#77 Feature/76 공공데이터받아오기
  client/happyhouse_client/src/api/apartment.js
  client/happyhouse_client/src/components/map/LeftBar.vue
  server/happyhouse_server/src/main/java/com/ssafy/house/user/dao/UserDAO.java
Labels: feautre

#85 Feature/84-지도-년,월 필터 - client
  client/happyhouse_client/src/components/map/SelectBoxes.vue
  client/happyhouse_client/src/views/MapView.vue
Labels: enhancement

#83 Feature/62-news client
  client/happyhouse_client/src/api/news.js
  client/happyhouse_client/src/components/home/NewsList.vue
Labels: enhancement

#87 Feature/86-search-store-client
  client/happyhouse_client/src/components/map/SelectBoxes.vue
  client/happyhouse_client/src/store/index.js
  client/happyhouse_client/src/store/modules/search-store.js
Labels: enhancement
