Repository two-whales-and-one-shrimp/happy_house, pull requests merged in 2023-01, with the labels that each got.

#89 Feature/88 구군코드전송 server
  server/happyhouse_server/src/main/java/com/ssafy/house/map/controller/MapController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/dao/MapDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/dao/impl/MapDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/data/dto/MapResultDto.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/service/MapService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/service/impl/MapServiceImpl.java
Labels: enhancement

#92 Feature/82-거래내역검색결과-client
  client/happyhouse_client/src/api/apartment.js
  client/happyhouse_client/src/components/map/LeftBar.vue
  client/happyhouse_client/src/components/map/TheKakaoMap.vue
  client/happyhouse_client/src/components/map/TradeSearchList.vue
  client/happyhouse_client/src/views/MapView.vue
Labels: enhancement

#93 Feature/80 자동완성키워드목록요청 client
  client/happyhouse_client/src/api/map.js
  client/happyhouse_client/src/components/home/NewsList.vue
  client/happyhouse_client/src/components/home/SearchBar.vue
  client/happyhouse_client/src/components/map/LeftBar.vue
Labels: feautre

#97 bug: 접근 권한 부여
  client/happyhouse_client/src/components/map/LeftBar.vue
  client/happyhouse_client/src/router/index.js
  server/happyhouse_server/src/main/java/com/ssafy/house/config/security/SecurityConfiguration.java
Labels: bug

#95 feat: 지역정보불러오기
  client/happyhouse_client/src/api/apartment.js
  client/happyhouse_client/src/api/map.js
  client/happyhouse_client/src/components/home/SearchBar.vue
  client/happyhouse_client/src/components/map/LeftBar.vue
  client/happyhouse_client/src/components/map/SelectBoxes.vue
  client/happyhouse_client/src/components/map/TheKakaoMap.vue
  client/happyhouse_client/src/store/modules/search-store.js
  server/happyhouse_server/src/main/java/com/ssafy/house/map/controller/MapController.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/dao/MapDAO.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/dao/impl/MapDAOImpl.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/data/dto/MapResultDto.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/data/repository/MapRepository.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/service/MapService.java
  server/happyhouse_server/src/main/java/com/ssafy/house/map/service/impl/MapServiceImpl.java
Labels: feautre

#99 Bug/98-지도검색
  client/happyhouse_client/src/api/map.js
  client/happyhouse_client/src/components/home/SearchBar.vue
  client/happyhouse_client/src/router/index.js
Labels: bug
